---
namespace: Titanium.Platform.openApplication
type: method
description: Launch an Android application use the helper method logInstalledApplicationNames to discover applications.
since: 0.4.0
platforms: ['android-1.5', 'iphone-2.2.1', 'iphone-3.0', 'iphone-3.0', 'iphone-3.1']
returns: bool
parameters: 
    - [string, app, Android application name.]
