---
namespace: Titanium.App
type: module
description: |
  <p>The top level App module. The App module is used
  for retrieving application built-time information such
  as the version of the application.</p>
since: 0.4
