---
namespace: Titanium.Database
type: module
description: |
  <p>The top level Database module. The Database module is used
  for interacting with the application's private SQLite database.</p>
since: 0.4
examples:
  - |
      Open a DB and run a simple SQL query.
      <pre><code>
      	var db = Titanium.DB.open("hello");
      	var results = db.execute("select * from bar where id = ?", 1);
      	results.close();
      	db.close();
      </code></pre>