---
namespace: Titanium.Filesystem.getApplicationDirectory
type: function
description: Returns file object pointing to the applications installation directory
since: 0.4.0
platforms: ['android', 'iphone']
returns: File
parameters: []
