---
namespace: Titanium.Filesystem.getApplicationDirectory
type: method
description: Returns file object pointing to the applications installation directory
since: 0.4.0
platforms: ['android-1.5', 'iphone-2.2.1', 'iphone-3.0', 'iphone-3.0', 'iphone-3.1']
returns: File
parameters: []
