---
namespace: Titanium.Filesystem.getApplicationDataDirectory
type: function
description: "Returns a file object pointing to the application's on device data directory."
since: 0.4.0
platforms: ['android', 'iphone']
returns: File
parameters: []
