---
namespace: Titanium.Filesystem.getApplicationMassDataDirectory
type: method
description: "Returns a file object pointing to the application's off device data directory."
since: 0.7.2
platforms: ['android-1.5', 'iphone-2.2.1', 'iphone-3.0', 'iphone-3.0', 'iphone-3.1']
returns: File
parameters: []
