---
namespace: Titanium.Analytics.settingsEvent
type: method
description: send an application settings event.
since: 0.7.0
platforms: ['android-1.5', 'iphone-2.2.1', 'iphone-3.0', 'iphone-3.0', 'iphone-3.1']
returns: String
parameters: 
    - [string, event, name of the event]
    - [Object, data, (optional) data to send with the event]
